### ISSUE TITLE
Inlining SVG as XML does not work in all browsers

### ISSUE THREAD

**Issue by PerlPong** [bezoerb/postcss-image-inliner#1]
The plugin does not base64-encode SVG images, but uses the XML directly. Unfortunately, this does not work in some browsers, such as IE11 (in my case). Please see this issue: https://github.com/borodean/postcss-assets/issues/24

Perhaps add a configuration option, such as "encodeSvg", to be safe and always base64-encode the SVG images?

**Comment by bezoerb** [comment]
@PerlPong thanks for the hint.
I've updated the default encoding for svg and added an option to force base64 encoding for svgs.
Wanna give it a try? I've only got ms edge to test on.

**Comment by PerlPong** [comment]
It works now, both with the forced encoding, and also without. Thank you.

One problem when I upgraded to 0.1.3 (using npm), the index.js file was missing from the directory node_modules/postcss-image-inliner/, and I had to manually copy it from the repository

````cp ../../repos/postcss-image-inliner/index.js node_modules/postcss-image-inliner/````

No idea why this happened, maybe you need to re-publish to npm?

**Comment by bezoerb** [comment]
Done
