### ISSUE TITLE
Custom command to inline?

### ISSUE THREAD

**Issue by benfrain** [bezoerb/postcss-image-inliner#10]
I have a situation where some assets I want to inline and some I don't. For example, SVG I want to inline but fallback PNG files I don't (I don't want fallback images as part of the render blocking CSS).

Is there any chance we could get an option to use a keyword to inline but otherwise not? For example:

```
background-image: inliner("path/to/image.svg");
```

Would inline that image but:

```
background-image: url("path/to/image.svg");
```

Would not.

Is this a possibility?

**Comment by Keksinautin** [comment]
I think it would be better to avoid using custom syntax in css files. Instead it is better to use some parameter while compilation. 
For example `exludePattern` that shows the files which must not be handled by `postcss-image-inliner`.

**Comment by bezoerb** [comment]
I would also go for the parameter or/and maybe some sort of annotation?
However, i'm quite busy at the moment and don't have much time to work on this.
Do you want to PR?

**Comment by Keksinautin** [comment]
Yes, I think I can do it during the week.

**Comment by bezoerb** [comment]
:+1:

**Comment by benfrain** [comment]
No problem, in that case then, this plugin probably won't suit my needs as I need to be selective as to which assets get inlined.

**Comment by bezoerb** [comment]
What about be selective by annotation?
```
/* inliner: true */
background-image: url("path/to/image.svg");

/* inliner: false */
background-image: url("path/to/another/image.svg");
```

and option `useAnnotation` ?

**Comment by bezoerb** [comment]
seems there's no need for this anymore
