### ISSUE TITLE
Huge performance degredation after upgrading to v2

### ISSUE THREAD

**Issue by evoyy** [bezoerb/postcss-image-inliner#209]
This tool has been working really well for me for a long time. However, after upgrading to version 2 I have a performance issue.

I have set up a minimal test case here: https://github.com/evoyy/postcss-image-inliner-testcase

If you clone this repo and run ````npm install```` and run the commands below you will see what I mean.

I'm using npm v5.6.0 and node v9.9.0.

**postcss-image-inliner@1.0.6:**

````
./node_modules/.bin/postcss --verbose --config postcss.config.js -o output.css input.css
Processing test.css...
Finished test.css in 322 ms
````

**postcss-image-inliner@2.0.0:**
````
./node_modules/.bin/postcss --verbose --config postcss.config.js -o output.css input.css
Processing test.css...
Finished test.css in 13 s
````

As you can see, there is a huge difference between v1 and v2. In my real app, v2 takes minutes to finish processing.

I think it may have something to do with the postcss config file. If I remove the config file, the issue is not present. But even if I use even an empty config, such as below, the issue is present:

````
module.exports = {
    plugins: {
        'postcss-image-inliner': { },
    },
};
````

**Comment by bezoerb** [comment]
Thanks @evoyy. I'll take a look what's causing these performance degradation

**Comment by evoyy** [comment]
Hi, I noticed that you did a rewrite recently so I upgraded to v3 and it seems that my issue is resolved.

In my test repo, v1.0.6 is about 25% faster than v3.0.0. But this doesn't really matter.

**Comment by bezoerb** [comment]
@evoyy: thanks for monitoring the performance. Maybe I find some ways to improve it ;)
