### ISSUE TITLE
Fix lgtm issues

### ISSUE THREAD

**Issue by XhmikosR** [bezoerb/postcss-image-inliner#224]
https://lgtm.com/projects/g/bezoerb/postcss-image-inliner/?mode=list

These might need to be backported to 2.x too.

@bezoerb no pressure, the backport I can do it myself after we have the new asset-resolver 1.x release.

**Comment by bezoerb** [comment]
Done [v3.0.6](https://github.com/bezoerb/postcss-image-inliner/releases/tag/v3.0.6)

**Comment by XhmikosR** [comment]
Thanks :)
