### ISSUE TITLE
Image inliner causes CSS compile time to double if not more.

### ISSUE THREAD

**Issue by JSpell** [bezoerb/postcss-image-inliner#228]
Recently I have had to unexpectedly upgrade my node environment due to server requirements that are out of my control.  Therefore my current working versions are below along with my `stylesTask` function that makes the call for `imageInliner`.  

With the node & gulp upgrades my build time has increase tremendously (17+ minutes).  If I comment out the `imageInliner` section from the `CSSProcessors` array my build will complete in less than a minute.

I have tried trouble shooting by narrowing it down to one small CSS file to build & adding small imports at a time. Each build completed in about 30 seconds after each save.  I added an import that included 4 images in the scss file & the build time goes from the 30 seconds to compile to a 2.5 minute compile of a 53 kb css file.

Can some one please let me know if there's something I am missing, need to update, or what?  

Thanks.

Node: v13.12.0
Gulp:
    CLI version: 2.2.0
    Local version: 4.0.2
gulp-postcss: 8.0.0
postcss-image-inliner: 3.0.9

Gulp file snippets

```
const CSSProcessors = [
    autoprefixer,
    imageInliner({
        maxFileSize: 10000,
        assetPaths: ["Feature/*/code/images/**", "Feature/*/code/Assets/**", "Foundation/*/code/images/**"]
    }),
    cssnano({
        discardDuplicates: false
    })
];

function stylesTask() {

    return gulp.src(paths.styles.src)
        .pipe(sourcemaps.init()) // start sourcemap processing
        .pipe(postcss(preCompileCSSProcessors, { syntax: postcssScss }))
        .on("error", errorHandler) // if there are errors during postcss, call errorHandler  
        .pipe(sass())
        .on("error", errorHandler) // if there are errors during sass, call errorHandler  
        .pipe(postcss(CSSProcessors))
        .pipe(rename(function (pathName) {
            pathName.extname = ".min.css"
            pathName.dirname = pathName.dirname.replace("\\code\\Styles", "");
        }))
        .pipe(gulp.dest(paths.styles.dest));
}
```

**Comment by bezoerb** [comment]
this looks like an issue on my side ;)
I'll take a look as soon as i got some free time

**Comment by evoyy** [comment]
This sounds like it's the same issue I was having in https://github.com/bezoerb/postcss-image-inliner/issues/209. I never tracked down the problem, luckily it went away after upgrading because this is a great little package. I recommend upgrading to node v14 then delete your node_modules directory and try a fresh `npm install`.

**Comment by bezoerb** [comment]
@JSpell: i made some improvements in one of the dependencies. Could you update to the latest version (v4.0.2) and give it another try?

**Comment by JSpell** [comment]
@bezoerb Thanks for tagging me.  I will be glad to give it another try just as soon as I can find some time. I'll report back when I can, thanks again.
