### ISSUE TITLE
Missing files and errors

### ISSUE THREAD

**Issue by jacwright** [bezoerb/postcss-image-inliner#28]
It would be great to have the option to fail if the file is missing. Or at the very least allow logging it without logging everything.

**Comment by bezoerb** [comment]
@jacwright i just added the `strict` option (master branch). Do you want to check if that fits your needs?

**Comment by jacwright** [comment]
Perfect!! That will be great. Thank you!

Now if we mistype an image in the stylesheet we'll know about it before it goes out.

Would you mind bumping and publishing the latest to npm?

**Comment by bezoerb** [comment]
@jacwright https://github.com/bezoerb/postcss-image-inliner/releases/tag/v0.2.0

**Comment by jacwright** [comment]
Yay!!
