### ISSUE TITLE
Image inliner for "content" property in pseudo-elements

### ISSUE THREAD

**Issue by u-v** [bezoerb/postcss-image-inliner#61]
It'd be great if we can use image inliner for "content" property in pseudo-elements.

`
.class::after { content: url('../base64/image.png'); }
`

currently it doesn't re-write url to base64 for this use case

**Comment by bezoerb** [comment]
@u-v [v0.3.0](https://github.com/bezoerb/postcss-image-inliner/releases/tag/v0.3.0) should fix this.

**Comment by u-v** [comment]
i've just created a pull request. thanks!

**Comment by bezoerb** [comment]
Thanks for bringing that up.
